version: '3.8'

services:
    redis:
        image: redis:latest
        container_name: my-redis
        ports:
            - "6379:6379"
        networks:
            - my-network

    mysql:
        image: mysql:latest
        container_name: my-mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: root
        ports:
            - "3306:3306"
        networks:
            - my-network

networks:
    my-network:
        driver: bridge